// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: rpc/proxy.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyClient interface {
	LocalProxy(ctx context.Context, in *LocalProxyReq, opts ...grpc.CallOption) (*LocalProxyResp, error)
	// Request for the local Aurae daemon to enter peering mode.
	PeerRequest(ctx context.Context, in *PeerRequestReq, opts ...grpc.CallOption) (*PeerRequestResp, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) LocalProxy(ctx context.Context, in *LocalProxyReq, opts ...grpc.CallOption) (*LocalProxyResp, error) {
	out := new(LocalProxyResp)
	err := c.cc.Invoke(ctx, "/aurae.Proxy/LocalProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) PeerRequest(ctx context.Context, in *PeerRequestReq, opts ...grpc.CallOption) (*PeerRequestResp, error) {
	out := new(PeerRequestResp)
	err := c.cc.Invoke(ctx, "/aurae.Proxy/PeerRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility
type ProxyServer interface {
	LocalProxy(context.Context, *LocalProxyReq) (*LocalProxyResp, error)
	// Request for the local Aurae daemon to enter peering mode.
	PeerRequest(context.Context, *PeerRequestReq) (*PeerRequestResp, error)
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (UnimplementedProxyServer) LocalProxy(context.Context, *LocalProxyReq) (*LocalProxyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalProxy not implemented")
}
func (UnimplementedProxyServer) PeerRequest(context.Context, *PeerRequestReq) (*PeerRequestResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeerRequest not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	s.RegisterService(&Proxy_ServiceDesc, srv)
}

func _Proxy_LocalProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalProxyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).LocalProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.Proxy/LocalProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).LocalProxy(ctx, req.(*LocalProxyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_PeerRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).PeerRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.Proxy/PeerRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).PeerRequest(ctx, req.(*PeerRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Proxy_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurae.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocalProxy",
			Handler:    _Proxy_LocalProxy_Handler,
		},
		{
			MethodName: "PeerRequest",
			Handler:    _Proxy_PeerRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/proxy.proto",
}
