//===========================================================================*\
//           MIT License Copyright (c) 2022 Kris Nóva <kris@nivenly.com>     *
//                                                                           *
//                ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                *
//                ┃   ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗   ┃                *
//                ┃   ████╗  ██║██╔═████╗██║   ██║██╔══██╗  ┃                *
//                ┃   ██╔██╗ ██║██║██╔██║██║   ██║███████║  ┃                *
//                ┃   ██║╚██╗██║████╔╝██║╚██╗ ██╔╝██╔══██║  ┃                *
//                ┃   ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║  ┃                *
//                ┃   ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝  ┃                *
//                ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                *
//                                                                           *
//                       This machine kills fascists.                        *
//                                                                           *
//\*===========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: rpc/proxy.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PeerRequestReq) Reset() {
	*x = PeerRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequestReq) ProtoMessage() {}

func (x *PeerRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequestReq.ProtoReflect.Descriptor instead.
func (*PeerRequestReq) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proto_rawDescGZIP(), []int{0}
}

type PeerRequestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *PeerRequestResp) Reset() {
	*x = PeerRequestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequestResp) ProtoMessage() {}

func (x *PeerRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequestResp.ProtoReflect.Descriptor instead.
func (*PeerRequestResp) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *PeerRequestResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LocalProxyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO We need to understand the minimal parameters here
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LocalProxyReq) Reset() {
	*x = LocalProxyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalProxyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalProxyReq) ProtoMessage() {}

func (x *LocalProxyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalProxyReq.ProtoReflect.Descriptor instead.
func (*LocalProxyReq) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *LocalProxyReq) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *LocalProxyReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LocalProxyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Socket   string `protobuf:"bytes,2,opt,name=socket,proto3" json:"socket,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Code     int32  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LocalProxyResp) Reset() {
	*x = LocalProxyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalProxyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalProxyResp) ProtoMessage() {}

func (x *LocalProxyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalProxyResp.ProtoReflect.Descriptor instead.
func (*LocalProxyResp) Descriptor() ([]byte, []int) {
	return file_rpc_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *LocalProxyResp) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *LocalProxyResp) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *LocalProxyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LocalProxyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_rpc_proxy_proto protoreflect.FileDescriptor

var file_rpc_proxy_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x61, 0x75, 0x72, 0x61, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x50, 0x65, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x0f, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x41, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x72, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x84, 0x01, 0x0a, 0x05, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x12, 0x3b, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x12, 0x14, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6b, 0x72, 0x69, 0x73, 0x2d, 0x6e, 0x6f, 0x76, 0x61, 0x2f, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2f,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proxy_proto_rawDescOnce sync.Once
	file_rpc_proxy_proto_rawDescData = file_rpc_proxy_proto_rawDesc
)

func file_rpc_proxy_proto_rawDescGZIP() []byte {
	file_rpc_proxy_proto_rawDescOnce.Do(func() {
		file_rpc_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proxy_proto_rawDescData)
	})
	return file_rpc_proxy_proto_rawDescData
}

var file_rpc_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_proxy_proto_goTypes = []interface{}{
	(*PeerRequestReq)(nil),  // 0: aurae.PeerRequestReq
	(*PeerRequestResp)(nil), // 1: aurae.PeerRequestResp
	(*LocalProxyReq)(nil),   // 2: aurae.LocalProxyReq
	(*LocalProxyResp)(nil),  // 3: aurae.LocalProxyResp
}
var file_rpc_proxy_proto_depIdxs = []int32{
	2, // 0: aurae.Proxy.LocalProxy:input_type -> aurae.LocalProxyReq
	0, // 1: aurae.Proxy.PeerRequest:input_type -> aurae.PeerRequestReq
	3, // 2: aurae.Proxy.LocalProxy:output_type -> aurae.LocalProxyResp
	1, // 3: aurae.Proxy.PeerRequest:output_type -> aurae.PeerRequestResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proxy_proto_init() }
func file_rpc_proxy_proto_init() {
	if File_rpc_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerRequestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalProxyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalProxyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proxy_proto_goTypes,
		DependencyIndexes: file_rpc_proxy_proto_depIdxs,
		MessageInfos:      file_rpc_proxy_proto_msgTypes,
	}.Build()
	File_rpc_proxy_proto = out.File
	file_rpc_proxy_proto_rawDesc = nil
	file_rpc_proxy_proto_goTypes = nil
	file_rpc_proxy_proto_depIdxs = nil
}
